version: '3.8'
services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: bookservicetest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./book-service/init_events_table.sql:/docker-entrypoint-initdb.d/init_events_table.sql
      - ./book-service/init_books_table.sql:/docker-entrypoint-initdb.d/init_books_table.sql

  redis-test:
    image: redis:7
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  book-service-test:
    build:
      context: ./book-service
    environment:
      PGHOST: postgres-test
      PGDATABASE: bookservicetest
      PGUSER: test
      PGPASSWORD: test
      REDIS_URL: redis://redis-test:6379
      PORT: 6002
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    ports:
      - "6002:6002"
    command: ["npm", "run", "start"]
